### ISSUE TITLE
Prototipo baixa fidelidade

### ISSUE THREAD

**Issue by luandiemer** [luandiemer/GoodFood#5]
As telas com o conteúdo visual do aplicativo foram quase todas feitas, faltam apenas alterações minimas sobre como se transfere de tela para tela

**Comment by luandiemer** [comment]
Desenvolvimento de novas telas para base da aplicaçaõ final.

**Comment by Lemos56** [comment]
https://www.figma.com/file/FdZ1WjyumaRK8zyQ6hJoET/Projeto-Feed?node-id=0-1&t=NPxv1qLfmpklnkii-0
